name: Installing Python

on: [push]

jobs:
  build:
      strategy:
        fail-fast: false
        max-parallel: 2
        matrix:
          os: [ubuntu-latest, ubuntu-20.04, windows-latest]
          runs-on: ${{ matrix.os }}
          py-version: [3.7, 3.8, 3.9]
      
      steps:
          - name: Set up Python
          - uses: actions/setup-python@v4
      with:
        python-version: ${{py-version}}
        
